In [ ]:
import torch
import torch.nn as nn   

In [ ]:
# inputs
# torch.manual_seed(42) # Used for reproducibility of results

inputs = torch.tensor([[1.0, 2.0 , 3.0], [4.0 , 5.0 , 6.0], [7.0, 8.0, 9.0]])

In [21]:
neuron = nn.Linear(3, 1)  # 3 inputs and 1 output
# neuron = nn.Linear(in_features=3, out_features=1)  # alternate way to define the linear layer

In [22]:
outputs = neuron(inputs)

In [23]:
outputs

tensor([[-2.2448],
        [-3.5916],
        [-4.9384]], grad_fn=<AddmmBackward0>)

$$z = \sum_{i=1}^{n} w_i x_i + b$$

In [ ]:
# verify the output shape
print("shape of outputs : ")
print(outputs.shape)  # should be [3, 1] since we have 3 samples and 1 output per sample

# verify output values => weighted sum
print("weights and bias : ")
print(neuron.weight, neuron.bias)  # check the weights and bias of the neuron


# manual calculation of outputs using the formula z = w*x + b

# outputs = inputs @ neuron.weight.t() + neuron.bias  
print("manual calculation of outputs : ")
print(inputs @ neuron.weight.t() + neuron.bias)  # manual calculation of outputs , .t() is used to transpose the weight matrix from [1, 3] to [3, 1] so that it can be multiplied with inputs of shape [3, 3]

shape of outputs : 
torch.Size([3, 1])
weights and bias : 
Parameter containing:
tensor([[-0.0671,  0.4407,  0.0676]], requires_grad=True) Parameter containing:
tensor([-0.0816], requires_grad=True)
manual calculation of outputs : 
tensor([[0.9355],
        [2.2591],
        [3.5827]], grad_fn=<AddBackward0>)


In [ ]:
# When run again, the weights and bias will be different since they are initialized randomly. The outputs will also be different.
# so , to keep it same we can use random seed to initialize the weights and bias. This will ensure that the weights and bias are initialized to the same values every time we run the code.
